apiVersion: v1
kind: InstallConfig
baseDomain: kni-edge.cloud
metadata:
  name: cluster
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 2
platform:
  gcp:
    projectID: kni-edge
    region: europe-west1
